### ISSUE TITLE
attempt to index global 'enhance' (a nil value)

### ISSUE THREAD

**Issue by theronpatrick** [enhance-co/defold-connector#6]
I'm trying to include enhance as a dependency in my Defold project. Usually that comes with a corresponding require call, something like:

`local enhance = require "enhance"`

However, I can't seem to get that to work. What do I need to do in order to reference the `enhance` object?

**Comment by theronpatrick** [comment]
If anyone else has this problem, try closing/opening the project. The library dependency didn't appear to be bringing in the project file, but after doing this the "enhance" variable was available for me to use.

**Comment by britzl** [comment]
If you add or change a dependency you also need to do Project->Fetch Libraries to get the dependency into your project. This is what happens when Defold loads up your project when the editor is started.
